services:
  cms-app:
    build: .
    container_name: goldco-cms
    ports:
      - "8090:80"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped

  cms-worker:
    build: .
    container_name: goldco-cms-scheduler
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}  # Add this line
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    command: python worker.py
    restart: unless-stopped
    depends_on:
      - cms-app